### ISSUE TITLE
TSConfig library setting `dom` causing issues on Node-only compilations

### ISSUE THREAD

**Issue by stazz** [velut/query-registry#300]
Hello!

I am using `query-registry` version `2.6.0`. In my `tsconfig.json`, I **don't** have `"dom"` as one of elements in `"library"` entry, because my library not aimed to be used in browsers.

Running `tsc` causes the following errors:
```
    node_modules/query-registry/dist/utils/errors.d.ts(11,24): error TS2304: Cannot find name 'Response'.
    node_modules/query-registry/dist/utils/errors.d.ts(16,15): error TS2304: Cannot find name 'Response'.
```

This is because `Response` is not part of globals in Node as it is in browser.

I can do workaround by creating new `.d.ts` file with the following content:
```ts
// fix-qr.d.ts
declare global {
  // To fix compilation errors with query-registry module
  interface Response {}
}

// To fix error:
// Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.ts(2669)
export {};
```

So this bug is not blocker. But not particularly nice either.

**Comment by stazz** [comment]
Alternatively, this config in `tsconfig.json` also fixes the problem:
```json
{
  "compilerOptions": {
     ...,
     "types": [ "node" ]
  }
}
```

At very least, these things probably should be mentioned in the documentation. :)

**Comment by velut** [comment]
Hi @stazz, 

Thanks for the detailed issue, you are right and adding `Response` there was probably an oversight.

I think that you can solve the issue by ignoring the declaration files during compilation by setting `skipLibCheck` to `true` in your `tsconfig.json`. See https://www.typescriptlang.org/tsconfig#skipLibCheck.
