### ISSUE TITLE
ability to fetch dependants

### ISSUE THREAD

**Issue by benmccann** [velut/query-registry#396]
I'd love to be able to fetch which libraries depend on a given library

E.g. https://www.npmjs.com/package/query-registry?activeTab=dependents

**Comment by benmccann** [comment]
Hmm. Doesn't appear to be available from the registry APIs though, so I'll close this. Thanks!

**Comment by velut** [comment]
Hi @benmccann,

as you said I don't think there is an official API for this for that but if you happen to find more info I could look into it.
